model_configs:
  "o3-mini":
    orchestrator_model: "o3-mini"
    worker_model: "gpt-4o-2024-11-20"
    evaluator_model: "gpt-4o-2024-11-20"
    generator_model: "gpt-4o-2024-11-20"
    orchestrator_base_url: "gpt"
    worker_base_url: "gpt"
    evaluator_base_url: "gpt"
    generator_base_url: "gpt"

  "o3-mini-large":
    orchestrator_model: "o3-mini"
    worker_model: "o3-mini"
    evaluator_model: "o3-mini"
    generator_model: "o3-mini"
    orchestrator_base_url: "gpt"
    worker_base_url: "gpt"
    evaluator_base_url: "gpt"
    generator_base_url: "gpt"

  "4o-mini":
    orchestrator_model: "gpt-4o-mini"
    worker_model: "gpt-4o-mini"
    evaluator_model: "gpt-4o-mini"
    generator_model: "gpt-4o-mini"
    orchestrator_base_url: "gpt"
    worker_base_url: "gpt"
    evaluator_base_url: "gpt"
    generator_base_url: "gpt"

  "4o":
    orchestrator_model: "gpt-4o-2024-11-20"
    worker_model: "gpt-4o-2024-11-20"
    evaluator_model: "gpt-4o-2024-11-20"
    generator_model: "gpt-4o-2024-11-20"
    orchestrator_base_url: "gpt"
    worker_base_url: "gpt"
    evaluator_base_url: "gpt"
    generator_base_url: "gpt"

  "vllm-faster":
    orchestrator_model: "Qwen25_32B_INT4"
    worker_model: "Mistral-Small-Instruct"
    evaluator_model: "Qwen25_7B_INT4"
    generator_model: "Qwen25_7B_INT4"
    orchestrator_base_url: "http://10.20.0.46:8000/v1"
    worker_base_url: "http://10.20.0.238:8000/v1"
    evaluator_base_url: "http://10.20.0.191:8001/v1"
    generator_base_url: "http://10.20.0.191:8001/v1"
  
  "vllm":
    orchestrator_model: "Qwen25_32B_INT4"
    worker_model: "Mistral-Small-Instruct"
    evaluator_model: "Qwen25_32B_INT4"
    generator_model: "Mistral-Small-Instruct-INT4"
    orchestrator_base_url: "http://10.20.0.46:8000/v1"
    worker_base_url: "http://10.20.0.238:8000/v1"
    evaluator_base_url: "http://10.20.0.46:8000/v1"
    generator_base_url: "http://10.20.0.46:8001/v1"
  
  "vllm-large":
    orchestrator_model: "Qwen25_32B_INT4"
    worker_model: "Mistral-Small-Instruct"
    evaluator_model: "Qwen25_72B_INT4"
    generator_model: "Mistral-Small-Instruct-INT4"
    orchestrator_base_url: "http://10.20.0.46:8000/v1"
    worker_base_url: "http://10.20.0.238:8000/v1"
    evaluator_base_url: "http://10.20.0.191:8000/v1"
    generator_base_url: "http://10.20.0.46:8001/v1"

  "vllm-fast":
    orchestrator_model: "Qwen25_32B_INT4"
    worker_model: "Mistral-Small-Instruct"
    evaluator_model: "Qwen25_32B_INT4"
    generator_model: "Mistral-Small-Instruct-INT4"
    orchestrator_base_url: "http://10.20.0.46:8000/v1"
    worker_base_url: "http://10.20.0.238:8000/v1"
    evaluator_base_url: "http://10.20.0.46:8000/v1"
    generator_base_url: "http://10.20.0.46:8001/v1"

  "vllm-superfast":
    orchestrator_model: "Mistral-Small-Instruct-INT4"
    worker_model: "Mistral-Small-Instruct"
    evaluator_model: "Qwen25_7B_INT4"
    generator_model: "Qwen25_7B_INT4"
    orchestrator_base_url: "http://10.20.0.46:8001/v1"
    worker_base_url: "http://10.20.0.238:8000/v1"
    evaluator_base_url: "http://10.20.0.191:8001/v1"
    generator_base_url: "http://10.20.0.191:8001/v1"

  "vllm-superlarge":
    orchestrator_model: "Qwen25_72B_INT4"
    worker_model: "Mistral-Small-Instruct"
    evaluator_model: "Qwen25_72B_INT4"
    generator_model: "Mistral-Small-Instruct-INT4"
    orchestrator_base_url: "http://10.20.0.51:8000/v1"
    worker_base_url: "http://10.20.0.238:8000/v1"
    evaluator_base_url: "http://10.20.0.191:8000/v1"
    generator_base_url: "http://10.20.0.46:8001/v1"
  
  "vllm-mixed":
    orchestrator_model: "Qwen25_32B_INT4"
    worker_model: "gpt-4o-mini"
    evaluator_model: "Qwen25_32B_INT4"
    generator_model: "Qwen25_32B_INT4"
    orchestrator_base_url: "http://10.20.0.46:8001/v1"
    worker_base_url: "gpt"
    evaluator_base_url: "http://10.20.0.46:8001/v1"
    generator_base_url: "http://10.20.0.46:8001/v1"

  "4o-mixed":
    orchestrator_model: "gpt-4o-2024-11-20"
    worker_model: "gpt-4o-mini"
    evaluator_model: "gpt-4o-2024-11-20"
    generator_model: "gpt-4o-mini"
    orchestrator_base_url: "gpt"
    worker_base_url: "gpt"
    evaluator_base_url: "gpt"
    generator_base_url: "gpt"
