<!-- SidebarQuestions Component -->
<template>
    <div id="sidebar-questions" class="accordion">
        <div v-for="(section, index) in this.getQuestions()"
             :key="index"
             class="accordion-item">

            <!-- header -->
            <div class="accordion-header text-center">
                <button class="accordion-button collapsed text-center" type="button"
                        @click="toggleSection(index)"
                        data-bs-toggle="collapse"
                        :data-bs-target="'#questions-' + index"
                        aria-expanded="false" :aria-controls="'#questions-' + index">
                    <span class="section-icon">{{ section.icon }}</span>
                    <span class="section-title">{{ section.header }}</span>
                </button>
            </div>

            <!-- body -->
            <div :id="'questions-' + index"
                 class="accordion-collapse collapse"
                 data-bs-parent="#sidebar-questions">
                <div class="accordion-body">
                    <div v-for="(q, qIndex) in section.questions"
                         :key="qIndex"
                         class="question-item"
                         @click="this.$emit('select-question', q.question)">
                        <span class="question-text">{{ q.question }}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Regenerate autogenerated questions button -->
    <div v-if="showRegenerateButton" class="regenerate-container">
        <button class="btn btn-primary w-100" type="button"
                @click="this.$emit('regenerateSampleQuestions')">
            <span class="fa fa-refresh"></span>{{ Localizer.get('regenerate')}}
        </button>
    </div>
</template>

<script>
import Localizer from "../Localizer.js";
import {sidebarQuestions} from "../Localizer.js";
import conf from "../../config.js";

export default {
    name: 'SidebarQuestions',
    emits: [
        'select-question',
        'select-category',
        'regenerateSampleQuestions'
    ],
    data() {
        return {
            showRegenerateButton: false,
        }
    },
    setup() {
        return { conf, Localizer };
    },
    methods: {
        getQuestions() {
            return sidebarQuestions[Localizer.language];
        },

        toggleSection(index, show = null) {
            if (index < 0) return;
            const toggle = document.getElementById('questions-' + index);
            if (! toggle) return;
            const collapse = bootstrap.Collapse.getOrCreateInstance(toggle);

            // show not set -> invert current state
            if (show === null) {
                show = ! toggle.classList.contains('show');
            }

            if (show) {
                collapse.show();
                const questions = this.getQuestions();
                const header = index in questions ? questions[index].header : 'none';
                this.showRegenerateButton = index === 4;
                this.$emit('select-category', header);
            } else {
                collapse.hide();
                this.showRegenerateButton = false;
                this.$emit('select-category', null);
            }
        },

        toggleSectionByHeader(header, show = null) {
            const index = this.getQuestions().findIndex(section => section.header === header);
            this.toggleSection(index, show);
        },

        expandSectionByHeader(header) {
            this.toggleSectionByHeader(header, true);
        }
    },

    mounted() {
        // attach listeners for category opening
        for (let i = 0; i < this.getQuestions()?.length; ++i) {
            const toggle = document.getElementById('questions-' + i);
            if (! toggle) continue;

            const header = this.getQuestions()[i].header;
            toggle.addEventListener('show.bs.collapse', () => {
                this.$emit('select-category', header);
            });
        }

        // open default category
        this.expandSectionByHeader(conf.DefaultQuestions);
    }
}
</script>

<style scoped>
.section-icon {
    margin-right: 0.75rem;
    font-size: 1.25rem;
    width: 1.5rem;
    text-align: center;
}

.section-title {
    flex: 1;
    font-weight: 500;
}

.question-item {
    display: flex;
    align-items: center;
    padding: 0.75rem 1rem;
    cursor: pointer;
    color: var(--text-primary-color);
    background-color: var(--background-color);
    border: 1px solid var(--border-color);
    transition: all 0.2s ease;
}

.question-item:hover {
    background-color: var(--surface-color);
    transform: translateY(-1px);
    box-shadow: var(--shadow-sm);
    border-color: var(--primary-color);
    color: var(--primary-color);
}

.question-text {
    flex: 1;
    font-size: 0.875rem;
    line-height: 1.4;
}
</style>