<!-- SidebarQuestions Component -->
<template>
    <div id="sidebar-questions" class="accordion">
        <div v-for="(section, index) in this.getQuestions()"
             :key="index"
             class="accordion-item">

            <!-- header -->
            <div class="accordion-header text-center">
                <button class="accordion-button collapsed text-center" type="button"
                        data-bs-toggle="collapse"
                        :data-bs-target="'#questions-' + index"
                        aria-expanded="false" :aria-controls="'#questions-' + index">
                    <span class="section-icon">{{ section.icon }}</span>
                    <span class="section-title">{{ section.header }}</span>
                </button>
            </div>

            <!-- body -->
            <div :id="'questions-' + index"
                 class="accordion-collapse collapse"
                 data-bs-parent="#sidebar-questions">
                <div class="accordion-body">
                    <div v-for="(q, qIndex) in section.questions"
                         :key="qIndex"
                         class="question-item"
                         :class="{ 'autogenerated-question': q.icon==='🪄' }"
                         @click="$emit('select-question', q.question)">
                        <span class="question-text">
                            <template v-if="q.icon==='🪄'">{{ q.icon }}</template>{{ q.question }}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import Localizer from "../Localizer.js";
import {sidebarQuestions} from "../Localizer.js";

export default {
    name: 'SidebarQuestions',
    methods: {
        getQuestions() {
            return sidebarQuestions[Localizer.language];
        },

        toggleSection(index, show = null) {
            if (index < 0) return;
            const toggle = document.getElementById('questions-' + index);
            if (! toggle) return;
            const collapse = bootstrap.Collapse.getOrCreateInstance(toggle);

            // show not set -> invert current state
            if (show === null) {
                show = ! toggle.classList.contains('show');
            }

            if (show) {
                collapse.show();
                const questions = this.getQuestions();
                const header = index in questions ? questions[index].header : 'none';
                this.$emit('category-selected', header);
            } else {
                collapse.hide();
                this.$emit('category-selected', null);
            }
        },

        toggleSectionByHeader(header, show = null) {
            const index = this.getQuestions().findIndex(section => section.header === header);
            this.toggleSection(index, show);
        },

        expandSectionByHeader(header) {
            this.toggleSectionByHeader(header, true);
        }
    }
}
</script>

<style scoped>
.section-icon {
    margin-right: 0.75rem;
    font-size: 1.25rem;
    width: 1.5rem;
    text-align: center;
}

.section-title {
    flex: 1;
    font-weight: 500;
}

.question-item {
    display: flex;
    align-items: center;
    padding: 0.75rem 1rem;
    cursor: pointer;
    color: var(--text-primary-color);
    background-color: var(--background-color);
    border: 1px solid var(--border-color);
    transition: all 0.2s ease;
}

.question-item:hover {
    background-color: var(--surface-color);
    transform: translateY(-1px);
    box-shadow: var(--shadow-sm);
    border-color: var(--primary-color);
    color: var(--primary-color);
}

.question-text {
    flex: 1;
    font-size: 0.875rem;
    line-height: 1.4;
}

.autogenerated-question {
    background-color: var(--primary-color);
}

.autogenerated-question:hover {
    background-color: var(--secondary-color);
    color: var(--text-primary-color);
    border-color: var(--text-primary-color);
}
</style> 