<!-- SidebarQuestions Component -->
<template>
<div class="container flex-grow-1 overflow-hidden overflow-y-auto">
    <InputDialogue ref="editDialog" />

    <div v-if="!isMobile" class="sidebar-title">
        {{ Localizer.get('tooltipSidebarPrompts') }}
        <i class="fa fa-edit ms-auto click-icon"
           :class="{'click-icon-active': isEditModeActive}"
           @click="isEditModeActive = !isEditModeActive"
           title="Edit Mode" />
    </div>

    <div id="sidebar-questions" class="accordion">
        <div v-for="(section, index) in Localizer.samplePrompts"
             v-show="section.visible"
             :key="index"
             class="accordion-item">

            <!-- header -->
            <div class="accordion-header text-center d-flex align-items-center" style="background-color: var(--background-color)">
                <button class="accordion-button collapsed text-center" type="button"
                        data-bs-toggle="collapse"
                        :data-bs-target="'#questions-' + index"
                        aria-expanded="false" :aria-controls="'questions-' + index" >
                    <span class="section-icon">{{ section.icon }}</span>
                    <span class="section-title">{{ section.header }}</span>
                    <i v-if="isEditModeActive"
                       class="fa fa-edit click-icon"
                       :class="{'disabled': !this.editingAllowed}"
                       @click.stop.prevent="this.editCategory(section)"
                    />
                </button>
            </div>

            <!-- body -->
            <div :id="'questions-' + index"
                 class="accordion-collapse collapse"
                 data-bs-parent="#sidebar-questions"
                 v-on:[bsCollapseEvent]="this.$emit('select-category', section.header)">
                <div class="accordion-body">

                    <!-- category questions -->
                    <div v-for="(q, qIndex) in section.questions"
                         :key="qIndex"
                         class="question-item"
                         @click="this.$emit('select-question', q.question)">
                        <span class="question-text">
                            <i v-if="section.id === 'autogenerated-questions' && isRegenerating"
                               :class="['fa', 'fa-ellipsis', 'fa-beat-fade', 'text-center', 'w-100']"
                            />
                            <span v-else class="mb-auto">{{ q.question }}</span>
                        </span>
                        <i v-if="isEditModeActive"
                           class="fa fa-pen-to-square p-1 mb-auto click-icon"
                           :class="{'disabled': !this.editingAllowed}"
                           @click.stop="this.editPrompt(section, q)"
                        />
                    </div>

                    <!-- add new prompt button -->
                    <div v-if="isEditModeActive"
                         class="question-item justify-content-center"
                         :class="{'disabled': !this.editingAllowed}"
                         :aria-disabled="!editingAllowed"
                         @click.stop="this.addNewPrompt(section)">
                        <i class="fa fa-plus me-1" />
                        <span>Add New Prompt</span>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div>
        <!-- add new category button -->
        <button class="btn btn-primary w-100 mt-3" type="button"
                :disabled="!editingAllowed"
                v-if="isEditModeActive"
                @click="this.addNewCategory()">
            <i class="fa fa-plus" />
            Add New Category
        </button>

        <!-- autogen questions button -->
        <button class="btn btn-primary w-100 mt-3" type="button"
                :disabled="isRegenerating || !editingAllowed"
                v-if="!isEditModeActive"
                @click="autogenerateSampleQuestions()">
            <i :class="['fa', 'fa-sync', isRegenerating ? 'fa-spin' : '']" />
            {{ Localizer.get('regenerate')}}
        </button>

        <!-- reset to defaults button -->
        <button class="btn btn-danger w-100 mt-3" type="button"
                :disabled="!editingAllowed"
                v-if="isEditModeActive"
                @click="this.resetPrompts()">
            <i class="fa fa-undo" />
            {{ Localizer.get('buttonConfigReset')}}
        </button>
    </div>
</div>
</template>

<script>
import Localizer from "../../Localizer.js";
import conf from "../../../config.js";
import backendClient from "../../utils.js";
import {nextTick} from "vue";
import {useDevice} from "../../useIsMobile.js";
import InputDialogue from "../InputDialogue.vue";

export default {
    name: 'SidebarQuestions',
    components: { InputDialogue },
    emits: [
        'select-question',
        'select-category',
    ],
    data() {
        return {
            isEditModeActive: false,
            editingAllowed: true,
            isRegenerating: false,
        }
    },
    setup() {
        const {isMobile} = useDevice();
        const bsCollapseEvent = 'show.bs.collapse';
        return { conf, Localizer, isMobile, bsCollapseEvent };
    },
    methods: {
        async autogenerateSampleQuestions(numQuestions = 5) {
            this.isRegenerating = true;
            try {
                const newQuestions = {
                    id: "autogenerated-questions",
                    header: Localizer.get('autogenQuestionsTitle'),
                    icon: "🪄",
                    visible: true,
                    questions: (new Array(numQuestions)).map(() => ({
                        question: "__loading__",
                        icon: "",
                    }))
                };

                // Push new section or replace old questions with placeholders
                let prevIdx = Localizer.samplePrompts.findIndex(obj => obj.id === 'autogenerated-questions')
                let prevQuestions = null
                if (prevIdx === -1) {
                    Localizer.samplePrompts.push(newQuestions);
                    prevIdx = Localizer.samplePrompts.length - 1;
                } else {
                    prevQuestions = Localizer.samplePrompts[prevIdx].questions;
                    Localizer.samplePrompts[prevIdx] = newQuestions;
                }

                // Wait for initial push of questions and then show autogenerated questions
                await nextTick(() => this.expandSectionByHeader("Autogenerated Questions"))
                Localizer.reloadSampleQuestions("Autogenerated Questions");

                // Construct LLM request
                let user_query = "Based on your available tools, I want you to " +
                            `generate me exactly ${numQuestions} requests or questions a user could give you. These ${numQuestions} requests or ` +
                            "questions should directly reference one or more of your available tools. I want you to " +
                            "provide me your answer as a JSON file and NOTHING ELSE. Your response should look like this:" +
                            "" +
                            "{" +
                            "   '1': {'question': 'Example request...', 'icon': '🪄'}," +
                            "   '2': {'question': 'Example request...', 'icon': '🤖'}," +
                            "   '3': ..." +
                            "}";
                if (Localizer.language === 'DE') {
                    user_query += "\n\nGenerate all questions in German!";
                }
                // Make sure to not generate any of the previous questions
                if (prevQuestions) {
                    user_query += "\n\nPlease DO NOT generate the following questions:\n" +
                            JSON.stringify(prevQuestions);
                }

                // Let backend generate user questions
                const res = await backendClient.queryNoChat("simple-tools", user_query, false);
                const questions = res.content;
                try {
                    const parsedQuestions = JSON.parse(questions.slice(questions.indexOf('{'), questions.lastIndexOf('}') + 1));
                    newQuestions.questions = Object.values(parsedQuestions);
                    await backendClient.savePrompts(Localizer.samplePrompts);
                } catch (error) {
                    console.error('Failed to parse autogenerated questions.')
                    console.error(error);
                    console.er
                }

                // Replace autogenerated requests into sidebarQuestions
                Localizer.samplePrompts[prevIdx] = newQuestions;

                // save new prompts
                await backendClient.savePrompts(Localizer.samplePrompts);
            } catch (error) {
                console.log("ERROR " + error);
            } finally {
                this.isRegenerating = false;
            }
        },

        async loadPrompts() {
            Localizer.samplePrompts = await backendClient.getPrompts();
            Localizer.reloadSampleQuestions();
        },

        toggleSection(index, show = null) {
            if (index < 0) return;
            const toggle = document.getElementById('questions-' + index);
            if (! toggle) return;
            const collapse = bootstrap.Collapse.getOrCreateInstance(toggle);

            // show not set -> invert current state
            if (show === null) {
                show = ! toggle.classList.contains('show');
            }

            if (show) {
                collapse.show();
                const questions = Localizer.samplePrompts;
                const header = index in questions ? questions[index].header : 'none';
                this.$emit('select-category', header);
            } else {
                collapse.hide();
                this.$emit('select-category', null);
            }
        },

        toggleSectionByHeader(header, show = null) {
            const index = Localizer.samplePrompts.findIndex(section => section.header === header);
            this.toggleSection(index, show);
        },

        expandSectionByHeader(header) {
            this.toggleSectionByHeader(header, true);
        },

        async resetPrompts() {
            if (!confirm(Localizer.get('confirmSampleQuestionReset'))) return;
            this.editingAllowed = false;
            await backendClient.resetPrompts();
            Localizer.samplePrompts = await backendClient.getPrompts();
            Localizer.reloadSampleQuestions();
            this.editingAllowed = true;
        },

        addNewPrompt(category) {
            if (!this.editingAllowed) return;
            const schema = {question: { type: 'textarea', label: 'Prompt', default: "" }};
            this.$refs.editDialog.showDialogue('Add New Prompt', null, null, schema,
                values => this.handleAddPromptOk(values, category));
        },

        editPrompt(category, question) {
            if (!this.editingAllowed) return;
            const schema = {
                question: { type: 'textarea', label: 'Prompt', default: question.question, },
                delete: {type: 'checkbox', label: Localizer.get('checkboxDeleteFromPromptLibrary'), default: false, }
            };
            this.$refs.editDialog.showDialogue('Edit Prompt', null, null, schema,
                values => this.handleEditPromptOk(values, category, question));
        },

        addNewCategory() {
            if (!this.editingAllowed) return;
            const schema = {
                header: { type: 'text', label: 'Header' },
                icon: { type: 'text', label: 'Icon', default: "⭐" },
            };
            this.$refs.editDialog.showDialogue('Add New Category', null, null, schema,
                values => this.handleAddCategoryOk(values));
        },

        editCategory(category) {
            if (!this.editingAllowed) return;
            const schema = {
                header: { type: 'text', label: 'Header', default: category.header },
                icon: { type: 'text', label: 'Icon', default: category.icon },
                delete: {type: 'checkbox', label: Localizer.get('checkboxDeleteFromPromptLibrary'), default: false, }
            };
            this.$refs.editDialog.showDialogue('Edit Category', null, null, schema,
                values => this.handleEditCategoryOk(values, category));
        },

        async handleAddPromptOk(values, category) {
            if (!values.question) return;
            this.editingAllowed = false;
            category.questions.push({
                question: values.question,
                icon: "",
            });
            await backendClient.savePrompts(Localizer.samplePrompts);
            Localizer.reloadSampleQuestions();
            this.editingAllowed = true;
        },

        async handleEditPromptOk(values, category, question) {
            this.editingAllowed = false;
            if (values.delete) {
                const index = category.questions.indexOf(question);
                category.questions.splice(index, 1);
            } else {
                question.question = values.question;
            }
            await backendClient.savePrompts(Localizer.samplePrompts);
            Localizer.reloadSampleQuestions();
            this.editingAllowed = true;
        },

        async handleAddCategoryOk(values) {
            if (!values.header) return;
            this.editingAllowed = false;
            Localizer.samplePrompts.push({
                id: values.header,
                header: values.header,
                icon: values.icon,
                visible: true,
                questions: [],
            });

            // put autogenned questions at the end
            const index = Localizer.samplePrompts
                .findIndex(item => item.id === 'autogenerated-questions');
            if (index >= 0) {
                const [autogenCat] = Localizer.samplePrompts.splice(index, 1);
                Localizer.samplePrompts.push(autogenCat);
            }

            await backendClient.savePrompts(Localizer.samplePrompts);
            Localizer.reloadSampleQuestions();
            this.editingAllowed = true;
        },

        async handleEditCategoryOk(values, category) {
            this.editingAllowed = false;
            if (values.delete) {
                const index = Localizer.samplePrompts.indexOf(category);
                Localizer.samplePrompts.splice(index, 1);
            } else {
                category.header = values.header;
                category.icon = values.icon;
            }
            await backendClient.savePrompts(Localizer.samplePrompts);
            Localizer.reloadSampleQuestions();
            this.editingAllowed = true;
        },
    },

    async mounted() {
        Localizer.samplePrompts = await backendClient.getPrompts();

        // attach listeners for category opening
        for (let i = 0; i < Localizer.samplePrompts?.length; ++i) {
            const toggle = document.getElementById('questions-' + i);
            if (! toggle) continue;

            const header = Localizer.samplePrompts[i].header;
            toggle.addEventListener('show.bs.collapse', () => {
                this.$emit('select-category', header);
            });
        }

        // open default category
        this.expandSectionByHeader(conf.DefaultQuestions);
    }
}
</script>

<style scoped>
.section-icon {
    margin-right: 0.75rem;
    font-size: 1.25rem;
    width: 1.5rem;
    text-align: center;
}

.section-title {
    flex: 1;
    font-weight: 500;
}

.question-item {
    display: flex;
    align-items: center;
    padding: 0.75rem 0.25rem 0.75rem 0.75rem;
    cursor: pointer;
    color: var(--text-primary-color);
    background-color: var(--background-color);
    border: 1px solid var(--border-color);
    transition: all 0.2s ease;
}

.question-item:hover {
    background-color: var(--surface-color);
    transform: translateY(-1px);
    box-shadow: var(--shadow-sm);
    border-color: var(--primary-color);
    color: var(--primary-color);
}

.question-text {
    flex: 1;
    font-size: 0.875rem;
    line-height: 1.4;
    /* Limit to 3 lines and add ellipsis */
    display: -webkit-box;
    -webkit-line-clamp: 3;
    line-clamp: 3;
    -webkit-box-orient: vertical;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: normal;
}

.question-menu-button:hover {
    background-color: var(--input-color);
    color: var(--text-danger-color);
}

.click-icon {
    flex: 0 0 auto;
    width: 2rem;
    height: 2rem;
    font-size: 1rem;
    padding: 0;
    aspect-ratio: 1 / 1 !important;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    border-radius: 1rem !important;
    cursor: pointer;
    color: var(--text-primary-color);
}

.click-icon:hover {
    background-color: var(--input-color);
    color: var(--text-danger-color);
    transform: translateY(-1px);
}

.click-icon.click-icon-active {
    color: var(--primary-color) !important;
    border: 1px solid var(--primary-color);
}

.click-icon.disabled {
    opacity: 0.5;
    cursor: not-allowed;
    transform: none;
    color: var(--text-primary-color) !important;
    background: none !important;
}

.question-item.disabled {
    opacity: 0.5;
    cursor: not-allowed;
    transform: none;
    color: var(--text-primary-color) !important;
    border-color: var(--border-color) !important;
    background-color: var(--background-color) !important;
}

.accordion-header:hover .click-icon:hover {
    background-color: var(--primary-color);
}
</style>