<!-- SidebarQuestions Component -->
<template>
<div class="container flex-grow-1 overflow-hidden overflow-y-auto">
    <InputDialogue ref="editDialog" />

    <div v-if="!isMobile" class="sidebar-title">
        {{ Localizer.get('tooltipSidebarPrompts') }}
    </div>

    <div id="sidebar-questions" class="accordion">
        <div v-for="(section, index) in Localizer.samplePrompts"
             v-show="section.visible"
             :key="index"
             class="accordion-item">

            <!-- header -->
            <div class="accordion-header text-center">
                <button class="accordion-button collapsed text-center" type="button"
                        data-bs-toggle="collapse"
                        :data-bs-target="'#questions-' + index"
                        aria-expanded="false" :aria-controls="'questions-' + index">
                    <span class="section-icon">{{ section.icon }}</span>
                    <span class="section-title">{{ section.header }}</span>
                </button>
            </div>

            <!-- body -->
            <div :id="'questions-' + index"
                 class="accordion-collapse collapse"
                 data-bs-parent="#sidebar-questions"
                 v-on:[bsCollapseEvent]="this.$emit('select-category', section.header)">
                <div class="accordion-body">

                    <!-- category questions -->
                    <div v-for="(q, qIndex) in section.questions"
                         :key="qIndex"
                         class="question-item"
                         @click="this.$emit('select-question', q.question)">
                        <span class="question-text">
                            <i v-if="section.id === 'autogenerated-questions' && isRegenerating"
                               :class="['fa', 'fa-ellipsis', 'fa-beat-fade', 'text-center', 'w-100']"
                            />
                            <span v-else class="mb-auto">{{ q.question }}</span>
                        </span>
                        <i class="fa fa-pen-to-square p-1 mb-auto question-menu-button"
                           @click.stop="this.editQuestion(section, q)"
                        />
                    </div>

                </div>
            </div>
        </div>
    </div>

    <!-- Regenerate autogenerated questions button -->
    <div class="regenerate-container">
        <button class="btn btn-primary w-100" type="button"
                :disabled="isRegenerating"
                @click="autogenerateSampleQuestions()">
            <i :class="['fa', 'fa-sync', isRegenerating ? 'fa-spin' : '']"></i>{{ Localizer.get('regenerate')}}
        </button>
    </div>
</div>
</template>

<script>
import Localizer from "../../Localizer.js";
import conf from "../../../config.js";
import backendClient from "../../utils.js";
import {nextTick} from "vue";
import {useDevice} from "../../useIsMobile.js";
import InputDialogue from "../InputDialogue.vue";

export default {
    name: 'SidebarQuestions',
    components: { InputDialogue },
    emits: [
        'select-question',
        'select-category',
    ],
    data() {
        return {
            editingAllowed: true,
            isRegenerating: false,
            icon: "🔖",
            prompts: []
        }
    },
    setup() {
        const {isMobile} = useDevice();
        const bsCollapseEvent = 'show.bs.collapse';
        return { conf, Localizer, isMobile, bsCollapseEvent };
    },
    methods: {
        getQuestions() {
            return Localizer.samplePrompts;
        },

        async autogenerateSampleQuestions(numQuestions = 5) {
            this.isRegenerating = true;
            try {
                const newQuestions = {
                    "id": "autogenerated-questions",
                    "header": Localizer.get('autogenQuestionsTitle'),
                    "icon": "🪄",
                    "visible": true,
                    "questions": (new Array(numQuestions)).map(() => ({
                        question: "__loading__",
                        icon: "",
                    }))
                };

                // Push new section or replace old questions with placeholders
                let prevIdx = Localizer.samplePrompts.findIndex(obj => obj.id === 'autogenerated-questions')
                let prevQuestions = null
                if (prevIdx === -1) {
                    Localizer.samplePrompts.push(newQuestions);
                    prevIdx = Localizer.samplePrompts.length - 1;
                } else {
                    prevQuestions = Localizer.samplePrompts[prevIdx].questions;
                    Localizer.samplePrompts[prevIdx] = newQuestions;
                }

                // Wait for initial push of questions and then show autogenerated questions
                await nextTick(() => this.expandSectionByHeader("Autogenerated Questions"))
                Localizer.reloadSampleQuestions("Autogenerated Questions");

                // Construct LLM request
                let user_query = "Based on your available tools, I want you to " +
                            `generate me exactly ${numQuestions} requests or questions a user could give you. These ${numQuestions} requests or ` +
                            "questions should directly reference one or more of your available tools. I want you to " +
                            "provide me your answer as a JSON file and NOTHING ELSE. Your response should look like this:" +
                            "" +
                            "{" +
                            "   '1': {'question': 'Example request...', 'icon': '🪄'}," +
                            "   '2': {'question': 'Example request...', 'icon': '🤖'}," +
                            "   '3': ..." +
                            "}";
                if (Localizer.language === 'DE') {
                    user_query += "\n\nGenerate all questions in German!";
                }
                // Make sure to not generate any of the previous questions
                if (prevQuestions) {
                    user_query += "\n\nPlease DO NOT generate the following questions:\n" +
                            JSON.stringify(prevQuestions);
                }

                // Let backend generate user questions
                const res = await backendClient.queryNoChat("simple-tools", user_query, false);
                const questions = res.content;
                try {
                    const parsedQuestions = JSON.parse(questions.slice(questions.indexOf('{'), questions.lastIndexOf('}') + 1));
                    newQuestions.questions = Object.values(parsedQuestions);
                    await backendClient.savePrompts(Localizer.samplePrompts);
                } catch (error) {
                    console.error('Failed to parse autogenerated questions.')
                    console.error(error);
                }

                // Replace autogenerated requests into sidebarQuestions
                Localizer.samplePrompts[prevIdx] = newQuestions;

                // save new prompts
                await backendClient.savePrompts(Localizer.samplePrompts);
            } catch (error) {
                console.log("ERROR " + error);
            } finally {
                this.isRegenerating = false;
            }
        },

        async loadPrompts() {
            Localizer.samplePrompts = await backendClient.getPrompts();
            Localizer.reloadSampleQuestions();
        },

        toggleSection(index, show = null) {
            if (index < 0) return;
            const toggle = document.getElementById('questions-' + index);
            if (! toggle) return;
            const collapse = bootstrap.Collapse.getOrCreateInstance(toggle);

            // show not set -> invert current state
            if (show === null) {
                show = ! toggle.classList.contains('show');
            }

            if (show) {
                collapse.show();
                const questions = Localizer.samplePrompts;
                const header = index in questions ? questions[index].header : 'none';
                this.$emit('select-category', header);
            } else {
                collapse.hide();
                this.$emit('select-category', null);
            }
        },

        toggleSectionByHeader(header, show = null) {
            const index = Localizer.samplePrompts.findIndex(section => section.header === header);
            this.toggleSection(index, show);
        },

        expandSectionByHeader(header) {
            this.toggleSectionByHeader(header, true);
        },

        editQuestion(category, question) {
            if (!this.editingAllowed) return;
            const schema = {
                question: { type: 'textarea', label: 'Question', default: question.question, },
                delete: {type: 'checkbox', label: 'Delete?', default: false, }
            }
            this.$refs.editDialog.showDialogue('Edit Question', null, null, schema,
                values => this.handleEditOk(values, category, question));
        },

        async handleEditOk(values, category, question) {
            if (!values) return;
            this.editingAllowed = false;
            if (values.delete) {
                const index = category.questions.indexOf(question);
                category.questions.splice(index, 1);
            } else {
                question.question = values.question;
            }
            await backendClient.savePrompts(Localizer.samplePrompts);
            this.editingAllowed = true;
        }
    },

    async mounted() {
        Localizer.samplePrompts = await backendClient.getPrompts();

        // attach listeners for category opening
        for (let i = 0; i < Localizer.samplePrompts?.length; ++i) {
            const toggle = document.getElementById('questions-' + i);
            if (! toggle) continue;

            const header = Localizer.samplePrompts[i].header;
            toggle.addEventListener('show.bs.collapse', () => {
                this.$emit('select-category', header);
            });
        }

        // open default category
        this.expandSectionByHeader(conf.DefaultQuestions);

    }
}
</script>

<style scoped>
.section-icon {
    margin-right: 0.75rem;
    font-size: 1.25rem;
    width: 1.5rem;
    text-align: center;
}

.section-title {
    flex: 1;
    font-weight: 500;
}

.question-item {
    display: flex;
    align-items: center;
    padding: 0.75rem 0.25rem 0.75rem 0.75rem;
    cursor: pointer;
    color: var(--text-primary-color);
    background-color: var(--background-color);
    border: 1px solid var(--border-color);
    transition: all 0.2s ease;
}

.question-item:hover {
    background-color: var(--surface-color);
    transform: translateY(-1px);
    box-shadow: var(--shadow-sm);
    border-color: var(--primary-color);
    color: var(--primary-color);
}

.question-text {
    flex: 1;
    font-size: 0.875rem;
    line-height: 1.4;
    /* Limit to 3 lines and add ellipsis */
    display: -webkit-box;
    -webkit-line-clamp: 3;
    line-clamp: 3;
    -webkit-box-orient: vertical;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: normal;
}

.question-item:hover .question-menu-button {
    opacity: 1;
    pointer-events: auto;
}

.question-menu-button {
    flex: 0 0 auto;
    width: 2rem;
    height: 2rem;
    font-size: 1rem;
    padding: 0;
    aspect-ratio: 1 / 1 !important;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    border-radius: 0.75rem !important;
    cursor: pointer;
    color: var(--text-primary-color);
    opacity: 0;
    pointer-events: none;
}

.question-menu-button:hover {
    background-color: var(--input-color);
    color: var(--text-danger-color);
}
</style>