<!-- SidebarQuestions Component -->
<template>
    <div id="sidebar-questions" class="accordion">
        <div v-for="(section, index) in this.getQuestions()"
             :key="index"
             class="accordion-item">

            <!-- header -->
            <div class="accordion-header text-center">
                <button class="accordion-button collapsed text-center" type="button"
                        data-bs-toggle="collapse"
                        :data-bs-target="'#questions-' + index"
                        aria-expanded="false" :aria-controls="'#questions-' + index">
                    <span class="section-icon">{{ section.icon }}</span>
                    <span class="section-title">{{ section.header }}</span>
                </button>
            </div>

            <!-- body -->
            <div :id="'questions-' + index"
                 class="accordion-collapse collapse"
                 data-bs-parent="#sidebar-questions">
                <div class="accordion-body">
                    <div v-for="(q, qIndex) in section.questions"
                         :key="qIndex"
                         class="question-item"
                         @click="this.$emit('select-question', q.question)">
                        <span class="question-text">
                            <i v-if="section.id === 'autogenerated-questions' && isRegenerating"
                               :class="['fa', 'fa-ellipsis', 'fa-beat-fade', 'text-center', 'w-100']"
                            />
                            <i v-else>{{ q.question }}</i>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Regenerate autogenerated questions button -->
    <div class="regenerate-container">
        <button class="btn btn-primary w-100" type="button"
                :disabled="isRegenerating"
                @click="autogenerateSampleQuestions()">
            <i :class="['fa', 'fa-sync', isRegenerating ? 'fa-spin' : '']"></i>{{ Localizer.get('regenerate')}}
        </button>
    </div>
</template>

<script>
import Localizer, {sidebarQuestions} from "../../Localizer.js";
import conf from "../../../config.js";
import {sendRequest} from "../../utils.js";
import {nextTick} from "vue";

export default {
    name: 'SidebarQuestions',
    emits: [
        'select-question',
        'select-category',
    ],
    data() {
        return {
            isRegenerating: false,
        }
    },
    setup() {
        return { conf, Localizer };
    },
    methods: {
        getQuestions() {
            return sidebarQuestions[Localizer.language];
        },

        async autogenerateSampleQuestions(numQuestions = 5) {
            try {
                this.isRegenerating = true;

                const newQuestions = {
                    "id": "autogenerated-questions",
                    "header": "Autogenerated Questions",
                    "icon": "🪄",
                    "questions": Array.from({ length: numQuestions }).map(() => ({
                        question: "__loading__",
                        icon: "",
                    }))
                }

                // Push new section or replace old questions with placeholders
                let prevIdx = sidebarQuestions[Localizer.language].findIndex((obj) => obj.id === 'autogenerated-questions')
                let prevQuestions = null
                if (prevIdx === -1) {
                    sidebarQuestions[Localizer.language].push(newQuestions);
                    prevIdx = sidebarQuestions[Localizer.language].length - 1;
                } else {
                    prevQuestions = sidebarQuestions[Localizer.language][prevIdx].questions;
                    sidebarQuestions[Localizer.language][prevIdx] = newQuestions;
                }

                // Wait for initial push of questions and then show autogenerated questions
                await nextTick(() => this.expandSectionByHeader("Autogenerated Questions"))
                Localizer.reloadSampleQuestions("Autogenerated Questions");

                // Construct LLM request
                const body = {store_in_history: false, user_query: "Based on your available tools, I want you to " +
                            `generate me exactly ${numQuestions} requests or questions a user could give you. These ${numQuestions} requests or ` +
                            "questions should directly reference one or more of your available tools. I want you to " +
                            "provide me your answer as a JSON file and NOTHING ELSE. Your response should look like this:" +
                            "" +
                            "{" +
                            "   '1': {'question': 'Example request...', 'icon': '🪄'}," +
                            "   '2': {'question': 'Example request...', 'icon': '🤖'}," +
                            "   '3': ..." +
                            "}"};
                if (Localizer.language === 'DE') {
                    body.user_query += "\n\nGenerate all questions in German!";
                }
                // Make sure to not generate any of the previous questions
                if (prevQuestions) {
                    body.user_query += "\n\nPlease DO NOT generate the following questions:\n" +
                            JSON.stringify(prevQuestions);
                }

                // Let backend generate user questions
                const res = await sendRequest("POST", `${conf.BackendAddress}/tool-llm/query`, body);
                const questions = res.data.agent_messages[0].content;
                const parsedQuestions = JSON.parse(questions);
                newQuestions.questions = Object.values(parsedQuestions);

                // Replace autogenerated requests into sidebarQuestions
                sidebarQuestions[Localizer.language][prevIdx] = newQuestions;
                Localizer.reloadSampleQuestions("Autogenerated Questions");

                // Add event listener to new section
                const toggle = document.getElementById('questions-' + prevIdx);
                toggle.addEventListener('show.bs.collapse', () => {
                    this.$emit('select-category', 'Autogenerated Questions');
                });
            } catch (error) {
                console.log("ERROR " + error);
            } finally {
                this.isRegenerating = false;
            }
        },

        toggleSection(index, show = null) {
            if (index < 0) return;
            const toggle = document.getElementById('questions-' + index);
            if (! toggle) return;
            const collapse = bootstrap.Collapse.getOrCreateInstance(toggle);

            // show not set -> invert current state
            if (show === null) {
                show = ! toggle.classList.contains('show');
            }

            if (show) {
                collapse.show();
                const questions = this.getQuestions();
                const header = index in questions ? questions[index].header : 'none';
                this.$emit('select-category', header);
            } else {
                collapse.hide();
                this.$emit('select-category', null);
            }
        },

        toggleSectionByHeader(header, show = null) {
            const index = this.getQuestions().findIndex(section => section.header === header);
            this.toggleSection(index, show);
        },

        expandSectionByHeader(header) {
            this.toggleSectionByHeader(header, true);
        }
    },

    mounted() {
        // attach listeners for category opening
        for (let i = 0; i < this.getQuestions()?.length; ++i) {
            const toggle = document.getElementById('questions-' + i);
            if (! toggle) continue;

            const header = this.getQuestions()[i].header;
            toggle.addEventListener('show.bs.collapse', () => {
                this.$emit('select-category', header);
            });
        }

        // open default category
        this.expandSectionByHeader(conf.DefaultQuestions);
    }
}
</script>

<style scoped>
.section-icon {
    margin-right: 0.75rem;
    font-size: 1.25rem;
    width: 1.5rem;
    text-align: center;
}

.section-title {
    flex: 1;
    font-weight: 500;
}

.question-item {
    display: flex;
    align-items: center;
    padding: 0.75rem 1rem;
    cursor: pointer;
    color: var(--text-primary-color);
    background-color: var(--background-color);
    border: 1px solid var(--border-color);
    transition: all 0.2s ease;
}

.question-item:hover {
    background-color: var(--surface-color);
    transform: translateY(-1px);
    box-shadow: var(--shadow-sm);
    border-color: var(--primary-color);
    color: var(--primary-color);
}

.question-text {
    flex: 1;
    font-size: 0.875rem;
    line-height: 1.4;
}
</style>