model_configs:
  "4o-mini":
    orchestrator_model: "gpt-4o-mini"
    worker_model: "gpt-4o-mini"
    base_url: null
    worker_base_url: null
    orchestrator_backend_type: "openai"
    worker_backend_type: "openai"

  "4o":
    orchestrator_model: "gpt-4o-2024-11-20"
    worker_model: "gpt-4o-2024-11-20"
    base_url: null
    worker_base_url: null
    orchestrator_backend_type: "openai"
    worker_backend_type: "openai"

  "vllm":
    orchestrator_model: "Qwen25_72B_INT4"
    worker_model: "watt-tool-8B-FP8-Dynamic"
    base_url: "http://10.20.0.224:8000/v1"
    worker_base_url: "http://10.20.0.193:8001/v1"
    orchestrator_backend_type: "vllm"
    worker_backend_type: "vllm"
  
  "vllm-mixed":
    orchestrator_model: "Qwen25_72B_INT4"
    worker_model: "gpt-4o-mini"
    base_url: "http://10.20.0.224:8000/v1"
    worker_base_url: null
    orchestrator_backend_type: "vllm"
    worker_backend_type: "openai"

  "4o-mixed":
    orchestrator_model: "gpt-4o-2024-11-20"
    worker_model: "gpt-4o-mini"
    base_url: null
    worker_base_url: null
    orchestrator_backend_type: "openai"
    worker_backend_type: "openai"
