model_configs:
  "o3-mini":
    orchestrator_model: "o3-mini"
    worker_model: "gpt-4o-2024-11-20"
    base_url: null
    worker_base_url: null
    orchestrator_backend_type: "openai"
    worker_backend_type: "openai"

  "o3-mini-large":
    orchestrator_model: "o3-mini"
    worker_model: "o3-mini"
    base_url: null
    worker_base_url: null
    orchestrator_backend_type: "openai"
    worker_backend_type: "openai"

  "4o-mini":
    orchestrator_model: "gpt-4o-mini"
    worker_model: "gpt-4o-mini"
    base_url: null
    worker_base_url: null
    orchestrator_backend_type: "openai"
    worker_backend_type: "openai"

  "4o":
    orchestrator_model: "gpt-4o-2024-11-20"
    worker_model: "gpt-4o-2024-11-20"
    base_url: null
    worker_base_url: null
    orchestrator_backend_type: "openai"
    worker_backend_type: "openai"

  "vllm-fast":
    orchestrator_model: "Mistral-Small-Instruct-INT4"
    worker_model: "Mistral-Small-Instruct"
    base_url: "http://10.20.0.224:8001/v1"
    worker_base_url: "http://10.20.0.193:8000/v1"
    orchestrator_backend_type: "vllm"
    worker_backend_type: "vllm"
  
  "vllm":
    orchestrator_model: "Qwen25_32B_INT4"
    worker_model: "Mistral-Small-Instruct"
    base_url: "http://10.20.0.224:8000/v1"
    worker_base_url: "http://10.20.0.193:8000/v1"
    orchestrator_backend_type: "vllm"
    worker_backend_type: "vllm"

  "vllm-large":
    orchestrator_model: "Qwen25_72B_INT4"
    worker_model: "Mistral-Small-Instruct"
    base_url: "http://10.20.0.51:8000/v1"
    worker_base_url: "http://10.20.0.193:8000/v1"
    orchestrator_backend_type: "vllm"
    worker_backend_type: "vllm"
  
  "vllm-mixed":
    orchestrator_model: "Qwen25_32B_INT4"
    worker_model: "gpt-4o-mini"
    base_url: "http://10.20.0.224:8001/v1"
    worker_base_url: null
    orchestrator_backend_type: "vllm"
    worker_backend_type: "openai"

  "4o-mixed":
    orchestrator_model: "gpt-4o-2024-11-20"
    worker_model: "gpt-4o-mini"
    base_url: null
    worker_base_url: null
    orchestrator_backend_type: "openai"
    worker_backend_type: "openai"
